/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Restaurant;

import com.sun.glass.events.KeyEvent;
import java.util.Scanner;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Rezwan
 */
public class Restaurant extends javax.swing.JFrame {


    
    public Restaurant() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        bhuna_box = new javax.swing.JCheckBox();
        tehari_box = new javax.swing.JCheckBox();
        kacchi_box = new javax.swing.JCheckBox();
        bcheese_box = new javax.swing.JCheckBox();
        ccheese_box = new javax.swing.JCheckBox();
        fishsan_box = new javax.swing.JCheckBox();
        vegsan_box = new javax.swing.JCheckBox();
        chickensan_box = new javax.swing.JCheckBox();
        bhuna = new javax.swing.JTextField();
        kacchi = new javax.swing.JTextField();
        tehari = new javax.swing.JTextField();
        fishsan = new javax.swing.JTextField();
        ccheese = new javax.swing.JTextField();
        bcheese = new javax.swing.JTextField();
        vegsan = new javax.swing.JTextField();
        chicksan = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        hspcl_box = new javax.swing.JCheckBox();
        hspcl = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        mdew_box = new javax.swing.JCheckBox();
        ccola_box = new javax.swing.JCheckBox();
        sprite_box = new javax.swing.JCheckBox();
        sweetyo_box = new javax.swing.JCheckBox();
        eggpudd_box = new javax.swing.JCheckBox();
        vshake_box = new javax.swing.JCheckBox();
        chocolate_box = new javax.swing.JCheckBox();
        oreoshake_box = new javax.swing.JCheckBox();
        mdew = new javax.swing.JTextField();
        sprite = new javax.swing.JTextField();
        ccola = new javax.swing.JTextField();
        vshake = new javax.swing.JTextField();
        eggpudd = new javax.swing.JTextField();
        sweetyo = new javax.swing.JTextField();
        cshake = new javax.swing.JTextField();
        oreoshake = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        dessert_box = new javax.swing.JCheckBox();
        cheesed = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        subtotal = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        tax = new javax.swing.JButton();
        Total = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ttotal = new javax.swing.JTextField();
        stotal = new javax.swing.JTextField();
        tttotal = new javax.swing.JTextField();
        Total2 = new javax.swing.JButton();
        cpayed = new javax.swing.JTextField();
        cchange = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1150, 750));
        setType(java.awt.Window.Type.POPUP);

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        bhuna_box.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        bhuna_box.setText("Bhuna Khichuri");
        bhuna_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhuna_boxActionPerformed(evt);
            }
        });

        tehari_box.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        tehari_box.setText("Beef Tehari");
        tehari_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tehari_boxActionPerformed(evt);
            }
        });

        kacchi_box.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        kacchi_box.setText("Kacchi Biriyani");
        kacchi_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kacchi_boxActionPerformed(evt);
            }
        });

        bcheese_box.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        bcheese_box.setText("Beef Cheese");
        bcheese_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcheese_boxActionPerformed(evt);
            }
        });

        ccheese_box.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        ccheese_box.setText("Chicken Cheese");
        ccheese_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccheese_boxActionPerformed(evt);
            }
        });

        fishsan_box.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        fishsan_box.setText("Fish Sandwich");
        fishsan_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fishsan_boxActionPerformed(evt);
            }
        });

        vegsan_box.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        vegsan_box.setText("Vegetable Sandwich");
        vegsan_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vegsan_boxActionPerformed(evt);
            }
        });

        chickensan_box.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        chickensan_box.setText("Chicken Sandwich");
        chickensan_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chickensan_boxActionPerformed(evt);
            }
        });

        bhuna.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        bhuna.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bhuna.setEnabled(false);
        bhuna.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                bhunaKeyTyped(evt);
            }
        });

        kacchi.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        kacchi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        kacchi.setEnabled(false);
        kacchi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                kacchiKeyTyped(evt);
            }
        });

        tehari.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        tehari.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tehari.setEnabled(false);
        tehari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tehariActionPerformed(evt);
            }
        });
        tehari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tehariKeyTyped(evt);
            }
        });

        fishsan.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        fishsan.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fishsan.setEnabled(false);
        fishsan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fishsanKeyTyped(evt);
            }
        });

        ccheese.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        ccheese.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ccheese.setEnabled(false);
        ccheese.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ccheeseKeyTyped(evt);
            }
        });

        bcheese.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        bcheese.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bcheese.setEnabled(false);
        bcheese.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                bcheeseKeyTyped(evt);
            }
        });

        vegsan.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        vegsan.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        vegsan.setEnabled(false);
        vegsan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                vegsanKeyTyped(evt);
            }
        });

        chicksan.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        chicksan.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        chicksan.setEnabled(false);
        chicksan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                chicksanKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Full Meal");

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Burgers");

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Sandwich");

        hspcl_box.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        hspcl_box.setText("Hungry Special");
        hspcl_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hspcl_boxActionPerformed(evt);
            }
        });

        hspcl.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        hspcl.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hspcl.setEnabled(false);
        hspcl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hspclKeyTyped(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("(180 tk)");

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("(160 tk)");

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("(140 tk)");

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("(120 tk)");

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("(100 tk)");

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("(220 tk)");

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("(85 tk)");

        jLabel22.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("(90 tk)");

        jLabel23.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("(50 tk)");

        jLabel33.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel33.setText("Amount");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(tehari_box)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tehari, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(vegsan_box)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                                .addComponent(vegsan, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(chickensan_box)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(chicksan, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(47, 47, 47)
                                        .addComponent(jLabel15))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(49, 49, 49)
                                        .addComponent(jLabel21))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(50, 50, 50)
                                        .addComponent(jLabel22))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(47, 47, 47)
                                        .addComponent(jLabel17))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(49, 49, 49)
                                        .addComponent(jLabel16))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(52, 52, 52)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel18)
                                            .addComponent(jLabel19))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(kacchi_box)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(kacchi, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(bcheese_box))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bcheese, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(fishsan_box))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fishsan, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(bhuna_box)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bhuna, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(11, 11, 11))))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(hspcl_box)
                                    .addComponent(ccheese_box))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ccheese, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(hspcl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel20)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel23)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bhuna_box)
                    .addComponent(bhuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kacchi_box)
                    .addComponent(kacchi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tehari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tehari_box))
                .addGap(2, 2, 2)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bcheese_box)
                    .addComponent(bcheese, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addGap(3, 3, 3)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ccheese_box)
                    .addComponent(ccheese, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hspcl_box)
                    .addComponent(hspcl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chickensan_box)
                            .addComponent(chicksan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fishsan_box)
                            .addComponent(fishsan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel21)
                        .addGap(72, 72, 72)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vegsan_box)
                            .addComponent(vegsan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        mdew_box.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        mdew_box.setText("Mountain Dew");
        mdew_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mdew_boxActionPerformed(evt);
            }
        });

        ccola_box.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        ccola_box.setText("Coca Cola");
        ccola_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccola_boxActionPerformed(evt);
            }
        });

        sprite_box.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        sprite_box.setText("Sprite");
        sprite_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sprite_boxActionPerformed(evt);
            }
        });

        sweetyo_box.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        sweetyo_box.setText("Sweet Yogurt");
        sweetyo_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sweetyo_boxActionPerformed(evt);
            }
        });

        eggpudd_box.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        eggpudd_box.setText("Egg Pudding");
        eggpudd_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eggpudd_boxActionPerformed(evt);
            }
        });

        vshake_box.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        vshake_box.setText("Vanilla Shakes");
        vshake_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vshake_boxActionPerformed(evt);
            }
        });

        chocolate_box.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        chocolate_box.setText("Chocolate Milk");
        chocolate_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chocolate_boxActionPerformed(evt);
            }
        });

        oreoshake_box.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        oreoshake_box.setText("Oreo Shakes");
        oreoshake_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oreoshake_boxActionPerformed(evt);
            }
        });

        mdew.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        mdew.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mdew.setEnabled(false);
        mdew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mdewActionPerformed(evt);
            }
        });
        mdew.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mdewKeyTyped(evt);
            }
        });

        sprite.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        sprite.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sprite.setEnabled(false);
        sprite.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                spriteKeyTyped(evt);
            }
        });

        ccola.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        ccola.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ccola.setEnabled(false);
        ccola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccolaActionPerformed(evt);
            }
        });
        ccola.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ccolaKeyTyped(evt);
            }
        });

        vshake.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        vshake.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        vshake.setEnabled(false);
        vshake.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                vshakeKeyTyped(evt);
            }
        });

        eggpudd.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        eggpudd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        eggpudd.setEnabled(false);
        eggpudd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                eggpuddKeyTyped(evt);
            }
        });

        sweetyo.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        sweetyo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sweetyo.setEnabled(false);
        sweetyo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sweetyoKeyTyped(evt);
            }
        });

        cshake.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        cshake.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cshake.setEnabled(false);
        cshake.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cshakeKeyTyped(evt);
            }
        });

        oreoshake.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        oreoshake.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        oreoshake.setEnabled(false);
        oreoshake.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                oreoshakeKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("Drinks");

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("Desserts");

        jLabel9.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("Shakes");

        dessert_box.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        dessert_box.setText("Cheese Dessert");
        dessert_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dessert_boxActionPerformed(evt);
            }
        });

        cheesed.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        cheesed.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cheesed.setEnabled(false);
        cheesed.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cheesedKeyTyped(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("(35 tk)");

        jLabel25.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("(35 tk)");

        jLabel26.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setText("(35 tk)");

        jLabel27.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 0));
        jLabel27.setText("(150 tk)");

        jLabel28.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setText("(200 tk)");

        jLabel29.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 0, 0));
        jLabel29.setText("(250 tk)");

        jLabel30.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 0));
        jLabel30.setText("(120 tk)");

        jLabel31.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 0, 0));
        jLabel31.setText("(150 tk)");

        jLabel32.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 0, 0));
        jLabel32.setText("(220 tk)");

        jLabel34.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel34.setText("Amount");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel27))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel28))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel8Layout.createSequentialGroup()
                                    .addGap(50, 50, 50)
                                    .addComponent(jLabel29))
                                .addGroup(jPanel8Layout.createSequentialGroup()
                                    .addComponent(mdew_box)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel24)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(mdew, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel8Layout.createSequentialGroup()
                                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel8Layout.createSequentialGroup()
                                            .addComponent(ccola_box)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel26))
                                        .addGroup(jPanel8Layout.createSequentialGroup()
                                            .addComponent(sprite_box)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel25)))
                                    .addGap(58, 58, 58)
                                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(sprite, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ccola, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                    .addGap(46, 46, 46)
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel34)
                                    .addGap(18, 18, 18)))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addComponent(chocolate_box)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel32))
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addComponent(oreoshake_box)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel31))
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addComponent(vshake_box)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel30))
                                    .addComponent(dessert_box)
                                    .addComponent(eggpudd_box)
                                    .addComponent(sweetyo_box)
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addComponent(jLabel9)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sweetyo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(eggpudd, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cheesed, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(vshake, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cshake, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(oreoshake, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 9, Short.MAX_VALUE)))))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(13, 13, 13)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mdew_box)
                    .addComponent(mdew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addGap(10, 10, 10)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sprite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sprite_box)
                        .addComponent(jLabel25)))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(ccola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ccola_box)
                            .addComponent(jLabel26))
                        .addGap(33, 33, 33)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sweetyo_box)
                    .addComponent(sweetyo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eggpudd_box)
                    .addComponent(eggpudd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cheesed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dessert_box))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGap(26, 26, 26)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vshake_box)
                    .addComponent(jLabel30)
                    .addComponent(vshake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oreoshake_box)
                    .addComponent(jLabel31)
                    .addComponent(oreoshake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chocolate_box)
                    .addComponent(jLabel32)
                    .addComponent(cshake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
        );

        subtotal.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        subtotal.setText("SUB TOTAL");
        subtotal.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        subtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtotalActionPerformed(evt);
            }
        });

        Reset.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        Reset.setText("RESET");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });

        exit.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        exit.setText("EXIT");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        tax.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        tax.setText("TAX");
        tax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taxActionPerformed(evt);
            }
        });

        Total.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        Total.setText("Total");
        Total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("WELCOME TO HUNGRY NOW");

        ttotal.setEditable(false);
        ttotal.setFont(new java.awt.Font("Ebrima", 1, 30)); // NOI18N
        ttotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ttotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ttotalActionPerformed(evt);
            }
        });

        stotal.setEditable(false);
        stotal.setFont(new java.awt.Font("Ebrima", 1, 30)); // NOI18N
        stotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tttotal.setEditable(false);
        tttotal.setFont(new java.awt.Font("Ebrima", 1, 30)); // NOI18N
        tttotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Total2.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        Total2.setText("CHANGE");
        Total2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Total2ActionPerformed(evt);
            }
        });

        cpayed.setFont(new java.awt.Font("Ebrima", 1, 30)); // NOI18N
        cpayed.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        cchange.setEditable(false);
        cchange.setFont(new java.awt.Font("Ebrima", 1, 30)); // NOI18N
        cchange.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel10.setText("CASH PAYED");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tax, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ttotal))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(stotal, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Total, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tttotal)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Total2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(cchange))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(cpayed))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(331, 331, 331)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stotal, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ttotal, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Total, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cpayed, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Total2, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                            .addComponent(cchange))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bhuna_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhuna_boxActionPerformed
        // TODO add your handling code here:
        if(bhuna_box.isSelected())
        {
            bhuna.setEnabled(true);
            bhuna.requestFocus();
            
        }
        else{
            bhuna.setEnabled(false);
            
            
        }
    }//GEN-LAST:event_bhuna_boxActionPerformed

    private void mdew_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mdew_boxActionPerformed
        // TODO add your handling code here:
        if(mdew_box.isSelected())
        {
            mdew.setEnabled(true);
            mdew.requestFocus();
            
        }
        else{
            mdew.setEnabled(false);
            
        }
    }//GEN-LAST:event_mdew_boxActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        // TODO add your handling code here:
        // RESET ALL VALUES//
        bhuna.setText(null);
        kacchi.setText(null);
        tehari.setText(null);
        bcheese.setText(null);
        ccheese.setText(null);
        hspcl.setText(null);
        fishsan.setText(null);
        vegsan.setText(null);
        chicksan.setText(null);
        mdew.setText(null);
        sprite.setText(null);
        ccola.setText(null);
        sweetyo.setText(null);
        eggpudd.setText(null);
        cheesed.setText(null);
        vshake.setText(null);
        oreoshake.setText(null);
        cshake.setText(null);
        tttotal.setText(null);
        stotal.setText(null);
        ttotal.setText(null);
        cpayed.setText(null);
        
        cchange.setText(null);
        
        
        
        
        //RESET ALL VALUES//
        bhuna_box.setSelected(false);
        kacchi_box.setSelected(false);
        tehari_box.setSelected(false);
        bcheese_box.setSelected(false);
        ccheese_box.setSelected(false);
        hspcl_box.setSelected(false);
        fishsan_box.setSelected(false);
        chickensan_box.setSelected(false);
        vegsan_box.setSelected(false);
        mdew_box.setSelected(false);
        sprite_box.setSelected(false);
        ccola_box.setSelected(false);
        sweetyo_box.setSelected(false);
        eggpudd_box.setSelected(false);
        dessert_box.setSelected(false);
        vshake_box.setSelected(false);
        oreoshake_box.setSelected(false);
        chocolate_box.setSelected(false);
        
    }//GEN-LAST:event_ResetActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
        
        
    }//GEN-LAST:event_exitActionPerformed

    private void tehariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tehariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tehariActionPerformed

    private void bhunaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bhunaKeyTyped
        // TODO add your handling code here:
        char iNumber=evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
            ||(iNumber==KeyEvent.VK_BACKSPACE)
                    ||(iNumber==KeyEvent.VK_DELETE)){
        evt.consume();
    }
    }//GEN-LAST:event_bhunaKeyTyped

    private void kacchiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kacchiKeyTyped
        // TODO add your handling code here:
        char iNumber=evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
            ||(iNumber==KeyEvent.VK_BACKSPACE)
                    ||(iNumber==KeyEvent.VK_DELETE)){
        evt.consume();
    }
    }//GEN-LAST:event_kacchiKeyTyped

    private void tehariKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tehariKeyTyped
        // TODO add your handling code here:
        char iNumber=evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
            ||(iNumber==KeyEvent.VK_BACKSPACE)
                    ||(iNumber==KeyEvent.VK_DELETE)){
        evt.consume();
    }
    }//GEN-LAST:event_tehariKeyTyped

    private void bcheeseKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bcheeseKeyTyped
        // TODO add your handling code here:
        char iNumber=evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
            ||(iNumber==KeyEvent.VK_BACKSPACE)
                    ||(iNumber==KeyEvent.VK_DELETE)){
        evt.consume();
    }
    }//GEN-LAST:event_bcheeseKeyTyped

    private void ccheeseKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ccheeseKeyTyped
        // TODO add your handling code here:
        char iNumber=evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
            ||(iNumber==KeyEvent.VK_BACKSPACE)
                    ||(iNumber==KeyEvent.VK_DELETE)){
        evt.consume();
    }
    }//GEN-LAST:event_ccheeseKeyTyped

    private void hspclKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hspclKeyTyped
        // TODO add your handling code here:
        char iNumber=evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
            ||(iNumber==KeyEvent.VK_BACKSPACE)
                    ||(iNumber==KeyEvent.VK_DELETE)){
        evt.consume();
    }
    }//GEN-LAST:event_hspclKeyTyped

    private void fishsanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fishsanKeyTyped
        // TODO add your handling code here:
        char iNumber=evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
            ||(iNumber==KeyEvent.VK_BACKSPACE)
                    ||(iNumber==KeyEvent.VK_DELETE)){
        evt.consume();
    }
    }//GEN-LAST:event_fishsanKeyTyped

    private void chicksanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_chicksanKeyTyped
        // TODO add your handling code here:
        char iNumber=evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
            ||(iNumber==KeyEvent.VK_BACKSPACE)
                    ||(iNumber==KeyEvent.VK_DELETE)){
        evt.consume();
    }
    }//GEN-LAST:event_chicksanKeyTyped

    private void vegsanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vegsanKeyTyped
        // TODO add your handling code here:
        char iNumber=evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
            ||(iNumber==KeyEvent.VK_BACKSPACE)
                    ||(iNumber==KeyEvent.VK_DELETE)){
        evt.consume();
    }
    }//GEN-LAST:event_vegsanKeyTyped

    private void mdewKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mdewKeyTyped
        // TODO add your handling code here:
        char iNumber=evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
            ||(iNumber==KeyEvent.VK_BACKSPACE)
                    ||(iNumber==KeyEvent.VK_DELETE)){
        evt.consume();
    }
    }//GEN-LAST:event_mdewKeyTyped

    private void spriteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_spriteKeyTyped
        // TODO add your handling code here:
        char iNumber=evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
            ||(iNumber==KeyEvent.VK_BACKSPACE)
                    ||(iNumber==KeyEvent.VK_DELETE)){
        evt.consume();
    }
    }//GEN-LAST:event_spriteKeyTyped

    private void ccolaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ccolaKeyTyped
        // TODO add your handling code here:
        char iNumber=evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
            ||(iNumber==KeyEvent.VK_BACKSPACE)
                    ||(iNumber==KeyEvent.VK_DELETE)){
        evt.consume();
    }
    }//GEN-LAST:event_ccolaKeyTyped

    private void sweetyoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sweetyoKeyTyped
        // TODO add your handling code here:
        char iNumber=evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
            ||(iNumber==KeyEvent.VK_BACKSPACE)
                    ||(iNumber==KeyEvent.VK_DELETE)){
        evt.consume();
    }
    }//GEN-LAST:event_sweetyoKeyTyped

    private void eggpuddKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_eggpuddKeyTyped
        // TODO add your handling code here:
        char iNumber=evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
            ||(iNumber==KeyEvent.VK_BACKSPACE)
                    ||(iNumber==KeyEvent.VK_DELETE)){
        evt.consume();
    }
    }//GEN-LAST:event_eggpuddKeyTyped

    private void cheesedKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cheesedKeyTyped
        // TODO add your handling code here:
        char iNumber=evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
            ||(iNumber==KeyEvent.VK_BACKSPACE)
                    ||(iNumber==KeyEvent.VK_DELETE)){
        evt.consume();
    }
    }//GEN-LAST:event_cheesedKeyTyped

    private void vshakeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vshakeKeyTyped
        // TODO add your handling code here:
        char iNumber=evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
            ||(iNumber==KeyEvent.VK_BACKSPACE)
                    ||(iNumber==KeyEvent.VK_DELETE)){
        evt.consume();
    }
    }//GEN-LAST:event_vshakeKeyTyped

    private void oreoshakeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_oreoshakeKeyTyped
        // TODO add your handling code here:
        char iNumber=evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
            ||(iNumber==KeyEvent.VK_BACKSPACE)
                    ||(iNumber==KeyEvent.VK_DELETE)){
        evt.consume();
    }
    }//GEN-LAST:event_oreoshakeKeyTyped

    private void cshakeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cshakeKeyTyped
        // TODO add your handling code here:
        char iNumber=evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
            ||(iNumber==KeyEvent.VK_BACKSPACE)
                    ||(iNumber==KeyEvent.VK_DELETE)){
        evt.consume();
    }
    }//GEN-LAST:event_cshakeKeyTyped

    private void kacchi_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kacchi_boxActionPerformed
        // TODO add your handling code here:
        if(kacchi_box.isSelected())
        {
            kacchi.setEnabled(true);
            kacchi.requestFocus();
            
        }
        else{
            kacchi.setEnabled(false);
            
        }
    }//GEN-LAST:event_kacchi_boxActionPerformed

    private void tehari_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tehari_boxActionPerformed
        // TODO add your handling code here:
        if(tehari_box.isSelected())
        {
            tehari.setEnabled(true);
            tehari.requestFocus();
            
        }
        else{
            tehari.setEnabled(false);
            
        }
    }//GEN-LAST:event_tehari_boxActionPerformed

    private void bcheese_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcheese_boxActionPerformed
        // TODO add your handling code here:
        if(bcheese_box.isSelected())
        {
            bcheese.setEnabled(true);
            bcheese.requestFocus();
            
        }
        else{
            bcheese.setEnabled(false);
            
        }
    }//GEN-LAST:event_bcheese_boxActionPerformed

    private void ccheese_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccheese_boxActionPerformed
        // TODO add your handling code here:
        if(ccheese_box.isSelected())
        {
            ccheese.setEnabled(true);
            ccheese.requestFocus();
            
        }
        else{
            ccheese.setEnabled(false);
            
        }
    }//GEN-LAST:event_ccheese_boxActionPerformed

    private void hspcl_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hspcl_boxActionPerformed
        // TODO add your handling code here:
        if(hspcl_box.isSelected())
        {
            hspcl.setEnabled(true);
            hspcl.requestFocus();
            
        }
        else{
            hspcl.setEnabled(false);
            
        }
    }//GEN-LAST:event_hspcl_boxActionPerformed

    private void fishsan_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fishsan_boxActionPerformed
        // TODO add your handling code here:
        if(fishsan_box.isSelected())
        {
            fishsan.setEnabled(true);
            fishsan.requestFocus();
            
        }
        else{
            fishsan.setEnabled(false);
            
        }
    }//GEN-LAST:event_fishsan_boxActionPerformed

    private void chickensan_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chickensan_boxActionPerformed
        // TODO add your handling code here:
        if(chickensan_box.isSelected())
        {
            chicksan.setEnabled(true);
            chicksan.requestFocus();
            
        }
        else{
            chicksan.setEnabled(false);
            
        }
    }//GEN-LAST:event_chickensan_boxActionPerformed

    private void vegsan_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vegsan_boxActionPerformed
        // TODO add your handling code here:
        if(vegsan_box.isSelected())
        {
            vegsan.setEnabled(true);
            vegsan.requestFocus();
            
        }
        else{
            vegsan.setEnabled(false);
            
        }
    }//GEN-LAST:event_vegsan_boxActionPerformed

    private void sprite_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sprite_boxActionPerformed
        // TODO add your handling code here:
        if(sprite_box.isSelected())
        {
            sprite.setEnabled(true);
            sprite.requestFocus();
            
        }
        else{
            sprite.setEnabled(false);
            
        }
    }//GEN-LAST:event_sprite_boxActionPerformed

    private void ccola_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccola_boxActionPerformed
        // TODO add your handling code here:
        if(ccola_box.isSelected())
        {
            ccola.setEnabled(true);
            ccola.requestFocus();
            
        }
        else{
            ccola.setEnabled(false);
            
        }
    }//GEN-LAST:event_ccola_boxActionPerformed

    private void sweetyo_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sweetyo_boxActionPerformed
        // TODO add your handling code here:
        if(sweetyo_box.isSelected())
        {
            sweetyo.setEnabled(true);
            sweetyo.requestFocus();
            
        }
        else{
            sweetyo.setEnabled(false);
           
        }
    }//GEN-LAST:event_sweetyo_boxActionPerformed

    private void eggpudd_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eggpudd_boxActionPerformed
        // TODO add your handling code here:
        if(eggpudd_box.isSelected())
        {
            eggpudd.setEnabled(true);
            eggpudd.requestFocus();
            
        }
        else{
            eggpudd.setEnabled(false);
            
        }
    }//GEN-LAST:event_eggpudd_boxActionPerformed

    private void dessert_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dessert_boxActionPerformed
        // TODO add your handling code here:
        if(dessert_box.isSelected())
        {
            cheesed.setEnabled(true);
            cheesed.requestFocus();
            
        }
        else{
            cheesed.setEnabled(false);
            
        }
    }//GEN-LAST:event_dessert_boxActionPerformed

    private void vshake_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vshake_boxActionPerformed
        // TODO add your handling code here:
        if(vshake_box.isSelected())
        {
            vshake.setEnabled(true);
            vshake.requestFocus();
            
        }
        else{
            vshake.setEnabled(false);
            
        }
    }//GEN-LAST:event_vshake_boxActionPerformed

    private void oreoshake_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oreoshake_boxActionPerformed
        // TODO add your handling code here:
        if(oreoshake_box.isSelected())
        {
            oreoshake.setEnabled(true);
            oreoshake.requestFocus();
            
        }
        else{
            oreoshake.setEnabled(false);
            
        }
    }//GEN-LAST:event_oreoshake_boxActionPerformed

    private void chocolate_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chocolate_boxActionPerformed
        // TODO add your handling code here:
        if(chocolate_box.isSelected())
        {
            cshake.setEnabled(true);
            cshake.requestFocus();
            
        }
        else{
            cshake.setEnabled(false);
            
        }
    }//GEN-LAST:event_chocolate_boxActionPerformed
    double x1=0;
    double y1=0;
    double z1=0;
    double xyz1=0;
    
    private void subtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtotalActionPerformed
        // TODO add your handling code here
        
        int a =Integer.parseInt(bhuna.getText());
        int b =Integer.parseInt(kacchi.getText());
        int c =Integer.parseInt(tehari.getText());
        int d =Integer.parseInt(bcheese.getText());
        int e =Integer.parseInt(ccheese.getText());
        int f =Integer.parseInt(hspcl.getText());
        int g =Integer.parseInt(fishsan.getText());
        int h =Integer.parseInt(chicksan.getText());
        int i =Integer.parseInt(vegsan.getText());
        int j =Integer.parseInt(mdew.getText());
        int k =Integer.parseInt(sprite.getText());
        int l =Integer.parseInt(ccola.getText());
        int m =Integer.parseInt(sweetyo.getText());
        int n =Integer.parseInt(eggpudd.getText());
        int o =Integer.parseInt(cheesed.getText());
        int p =Integer.parseInt(vshake.getText());
        int q =Integer.parseInt(oreoshake.getText());
        int r =Integer.parseInt(cshake.getText());
        double xyz=Double.parseDouble(cpayed.getText());

       

        calculation v1= new calculation(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r);
        
        x1=v1.bill();
        
        y1=v1.tax();
        
        z1=v1.sub_total();
        
        xyz1=v1.change();
        
        stotal.setText(""+x1);
        
        
        
//        jLabel2.setText(" BILL: "+x1);
        
//        JOptionPane.showMessageDialog(null, "SUB TOTAL:  "+ String.valueOf(x1));
  
        
        
    }//GEN-LAST:event_subtotalActionPerformed

    private void mdewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mdewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mdewActionPerformed

    private void ccolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccolaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ccolaActionPerformed

    private void taxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taxActionPerformed
        // TODO add your handling code here:
        
//        JOptionPane.showMessageDialog(null, "TAX :  "+ String.valueOf(y1));

        ttotal.setText(""+y1);
        
        
    }//GEN-LAST:event_taxActionPerformed

    private void TotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalActionPerformed
        // TODO add your handling code here:
//        JOptionPane.showMessageDialog(null, "FULL TOTAL  :  "+ String.valueOf(z1));

            tttotal.setText(""+z1);
        
    }//GEN-LAST:event_TotalActionPerformed

    private void ttotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ttotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ttotalActionPerformed

    private void Total2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Total2ActionPerformed
        // TODO add your handling code here:

       
        cchange.setText(""+xyz1);
        
        
        
    }//GEN-LAST:event_Total2ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Restaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Restaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Restaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Restaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Restaurant().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Reset;
    private javax.swing.JButton Total;
    private javax.swing.JButton Total2;
    private javax.swing.JTextField bcheese;
    private javax.swing.JCheckBox bcheese_box;
    private javax.swing.JTextField bhuna;
    private javax.swing.JCheckBox bhuna_box;
    private javax.swing.JTextField cchange;
    private javax.swing.JTextField ccheese;
    private javax.swing.JCheckBox ccheese_box;
    private javax.swing.JTextField ccola;
    private javax.swing.JCheckBox ccola_box;
    private javax.swing.JTextField cheesed;
    private javax.swing.JCheckBox chickensan_box;
    private javax.swing.JTextField chicksan;
    private javax.swing.JCheckBox chocolate_box;
    private javax.swing.JTextField cpayed;
    private javax.swing.JTextField cshake;
    private javax.swing.JCheckBox dessert_box;
    private javax.swing.JTextField eggpudd;
    private javax.swing.JCheckBox eggpudd_box;
    private javax.swing.JButton exit;
    private javax.swing.JTextField fishsan;
    private javax.swing.JCheckBox fishsan_box;
    private javax.swing.JTextField hspcl;
    private javax.swing.JCheckBox hspcl_box;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTextField kacchi;
    private javax.swing.JCheckBox kacchi_box;
    private javax.swing.JTextField mdew;
    private javax.swing.JCheckBox mdew_box;
    private javax.swing.JTextField oreoshake;
    private javax.swing.JCheckBox oreoshake_box;
    private javax.swing.JTextField sprite;
    private javax.swing.JCheckBox sprite_box;
    private javax.swing.JTextField stotal;
    private javax.swing.JButton subtotal;
    private javax.swing.JTextField sweetyo;
    private javax.swing.JCheckBox sweetyo_box;
    private javax.swing.JButton tax;
    private javax.swing.JTextField tehari;
    private javax.swing.JCheckBox tehari_box;
    private javax.swing.JTextField ttotal;
    private javax.swing.JTextField tttotal;
    private javax.swing.JTextField vegsan;
    private javax.swing.JCheckBox vegsan_box;
    private javax.swing.JTextField vshake;
    private javax.swing.JCheckBox vshake_box;
    // End of variables declaration//GEN-END:variables
}
